# Reticulum Party Line - Distrobox manifest
# Usage: distrobox assemble create --file distrobox.ini
# Docs:  https://distrobox.it/usage/distrobox-assemble/

[partyline-rns]
image=docker.io/marcusholtz/reticulum-party-line-box:latest
pull=false
replace=false
init=false
root=false
exported_bins=/usr/local/bin/rns-party-line.sh
exported_bins_path=~/.local/bin
